package vista;

import modelo.Equipo;

/**
 *
 * @author javie
 */
public class AñadirJugador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AñadirJugador.class.getName());

    /**
     * Creates new form AñadirJugador
     */
    public AñadirJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jComboBoxAñadirCiclista = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnModJugador = new javax.swing.JButton();
        jLabelDorsal = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelNombre3 = new javax.swing.JLabel();
        jComboBoxEquiposJug = new javax.swing.JComboBox<>();
        btnBorrarJugador = new javax.swing.JButton();
        btnAddJugador1 = new javax.swing.JButton();
        txtDorsal = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabelNombre.setText("Nombre:");

        jComboBoxAñadirCiclista.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        btnModJugador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnModJugador.setText("Modificar  Jugador");
        btnModJugador.addActionListener(this::btnModJugadorActionPerformed);
        jPanel1.add(btnModJugador);
        btnModJugador.setBounds(150, 260, 195, 33);

        jLabelDorsal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelDorsal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorsal.setText("Dorsal:");
        jLabelDorsal.setOpaque(true);
        jPanel1.add(jLabelDorsal);
        jLabelDorsal.setBounds(400, 220, 63, 22);

        jLabelNombre1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Nombre:");
        jLabelNombre1.setOpaque(true);
        jPanel1.add(jLabelNombre1);
        jLabelNombre1.setBounds(400, 260, 77, 22);

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(480, 260, 142, 26);

        jLabelNombre3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre3.setText("Equipos:");
        jLabelNombre3.setOpaque(true);
        jPanel1.add(jLabelNombre3);
        jLabelNombre3.setBounds(400, 310, 78, 22);

        jComboBoxEquiposJug.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxEquiposJug.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxEquiposJug.setToolTipText("");
        jComboBoxEquiposJug.addActionListener(this::jComboBoxEquiposJugActionPerformed);
        jPanel1.add(jComboBoxEquiposJug);
        jComboBoxEquiposJug.setBounds(480, 310, 129, 26);

        btnBorrarJugador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBorrarJugador.setText("Borrar Jugador");
        btnBorrarJugador.addActionListener(this::btnBorrarJugadorActionPerformed);
        jPanel1.add(btnBorrarJugador);
        btnBorrarJugador.setBounds(150, 310, 165, 33);

        btnAddJugador1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddJugador1.setText("Añadir Jugador");
        btnAddJugador1.addActionListener(this::btnAddJugador1ActionPerformed);
        jPanel1.add(btnAddJugador1);
        btnAddJugador1.setBounds(150, 210, 167, 33);

        txtDorsal.setBackground(new java.awt.Color(0, 0, 0));
        txtDorsal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtDorsal);
        txtDorsal.setBounds(470, 220, 110, 26);

        btnVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel1.add(btnVolver);
        btnVolver.setBounds(690, 570, 110, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestionJugadores (1).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-3, 6, 910, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModJugadorActionPerformed

    private void jComboBoxEquiposJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEquiposJugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEquiposJugActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBorrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarJugadorActionPerformed

    private void btnAddJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddJugador1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AñadirJugador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddJugador1;
    public javax.swing.JButton btnBorrarJugador;
    public javax.swing.JButton btnModJugador;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> jComboBoxAñadirCiclista;
    public javax.swing.JComboBox<Equipo> jComboBoxEquiposJug;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDorsal;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtDorsal;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
