package vista;


/**
 *
 * @author javie
 */
public class Juego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Juego.class.getName());

    /**
     * Creates new form Juego
     */
   public Juego() {
    initComponents();
    try {
        java.awt.Image img = javax.imageio.ImageIO.read(
            new java.io.File("src/main/resources/imagenes/porteria.jpg")
        );
        jLabel1.setIcon(new javax.swing.ImageIcon(img));
    } catch (Exception e) {
        System.out.println("No se pudo cargar la imagen: " + e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnZona2 = new javax.swing.JButton();
        btnZona4 = new javax.swing.JButton();
        btnZona3 = new javax.swing.JButton();
        btnZona5 = new javax.swing.JButton();
        lblMarcador = new javax.swing.JLabel();
        lblTurno1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnZona1 = new javax.swing.JButton();
        lblPenalti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnZona2.setText("Zona2");
        btnZona2.addActionListener(this::btnZona2ActionPerformed);
        jPanel1.add(btnZona2);
        btnZona2.setBounds(180, 550, 76, 27);

        btnZona4.setText("Zona4");
        jPanel1.add(btnZona4);
        btnZona4.setBounds(690, 350, 76, 27);

        btnZona3.setText("Zona3");
        jPanel1.add(btnZona3);
        btnZona3.setBounds(440, 460, 76, 27);

        btnZona5.setText("Zona5");
        btnZona5.setToolTipText("");
        jPanel1.add(btnZona5);
        btnZona5.setBounds(700, 550, 76, 27);

        lblMarcador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblMarcador.setText("0 - 0");
        jPanel1.add(lblMarcador);
        lblMarcador.setBounds(450, 50, 60, 28);

        lblTurno1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTurno1.setText("Turno de: Jugador 1");
        jPanel1.add(lblTurno1);
        lblTurno1.setBounds(0, 50, 430, 28);

        lblResultado.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 0));
        lblResultado.setText("!GOL!");
        jPanel1.add(lblResultado);
        lblResultado.setBounds(350, 140, 270, 40);

        btnZona1.setText("Zona 1");
        jPanel1.add(btnZona1);
        btnZona1.setBounds(170, 350, 76, 27);

        lblPenalti.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPenalti.setText("Penalti 1 de 5");
        jPanel1.add(lblPenalti);
        lblPenalti.setBounds(670, 50, 160, 28);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 98, 930, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZona2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZona2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Juego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnZona1;
    public javax.swing.JButton btnZona2;
    public javax.swing.JButton btnZona3;
    public javax.swing.JButton btnZona4;
    public javax.swing.JButton btnZona5;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblMarcador;
    public javax.swing.JLabel lblPenalti;
    public javax.swing.JLabel lblResultado;
    public javax.swing.JLabel lblTurno1;
    // End of variables declaration//GEN-END:variables
}
